name = "crawling-system"
main = "api-worker.js"
compatibility_date = "2025-06-12"
account_id = "d487a4f4ab6dd57899955ec5775f10ce"

[dev]
port = 8787
local_protocol = "http"

[[durable_objects.bindings]]
name = "COORDINATOR"
class_name = "CrawlingCoordinator"

[[durable_objects.bindings]]
name = "WEBSOCKET_HANDLER"
class_name = "WebSocketHandler"

[[migrations]]
tag = "v1"
new_classes = ["CrawlingCoordinator", "WebSocketHandler"]

[vars]
ENVIRONMENT = "development"

# 로컬 개발시 static assets 서빙
[site]
bucket = "./public"